ci: make cdbg deploy errors easier to spot
Co-authored-by: Daniel Weiße <66256922+daniel-weisse@users.noreply.github.com>

diff --git a/.github/actions/cdbg_deploy/action.yml b/.github/actions/cdbg_deploy/action.yml
--- a/.github/actions/cdbg_deploy/action.yml
+++ b/.github/actions/cdbg_deploy/action.yml
@@ -112,4 +112,8 @@ runs:
           --info logcollect.deployment-type="debugd" \
           --verbosity=-1 \
           --force
+          if [[ $? -ne 0 ]]; then
+            echo "::error::cdbg deploy failed"
+            exit 1
+          fi
         echo "::endgroup::"
