exit on newline and tagging with workflow id

diff --git a/.github/actions/e2e_test/action.yml b/.github/actions/e2e_test/action.yml
--- a/.github/actions/e2e_test/action.yml
+++ b/.github/actions/e2e_test/action.yml
@@ -126,7 +126,8 @@ runs:
       shell: bash
       run: |
         if [[ "${{ inputs.cosignPassword }}" == '' || "${{ inputs.cosignPrivateKey }}" == '' ]]; then
-          echo "::error::e2e test verify requires cosignPassword and cosignPrivateKey to be set." exit 1
+          echo "::error::e2e test verify requires cosignPassword and cosignPrivateKey to be set." 
+          exit 1
         fi
 
     - name: Determine build target
@@ -257,7 +258,7 @@ runs:
         gcpProjectID: ${{ inputs.gcpProject }}
         gcpZone: ${{ inputs.regionZone || 'europe-west3-b' }}
         kubernetesVersion: ${{ inputs.kubernetesVersion }}
-        additionalTags: "run-name=${{ steps.create-prefix.outputs.prefix }}"
+        additionalTags: "workflow=${{ github.workflow }}"
 
     - name: Login to GCP (Cluster service account)
       if: inputs.cloudProvider == 'gcp'
