fix: don't run CI K-Bench with less than 2 worker nodes
K-Bench's network benchmarks require two distinct worker nodes.
Add check prior to running the benchmark that terminates early, if not
enough workers scheduled.

diff --git a/.github/actions/e2e_test/action.yml b/.github/actions/e2e_test/action.yml
--- a/.github/actions/e2e_test/action.yml
+++ b/.github/actions/e2e_test/action.yml
@@ -56,6 +56,16 @@ runs:
         echo "Invalid input for test field: ${{ inputs.test }}"
         exit 1
 
+    # K-Bench's network benchmarks require at least two distinct worker nodes.
+    - name: Validate k-bench inputs
+      if: inputs.test == 'k-bench'
+      shell: bash
+      run: |
+        if [[ "${{ inputs.workerNodesCount }}" -lt 2 ]]; then
+          echo "::error::Test K-Bench requires at least 2 worker nodes."
+          exit 1
+        fi
+
     - name: Determine build target
       id: determine-build-target
       shell: bash
