ci: allow setting region/zone for e2e tests (#2205)
Signed-off-by: Daniel Weiße <dw@edgeless.systems>

diff --git a/.github/workflows/e2e-upgrade.yml b/.github/workflows/e2e-upgrade.yml
--- a/.github/workflows/e2e-upgrade.yml
+++ b/.github/workflows/e2e-upgrade.yml
@@ -11,12 +11,10 @@ on:
           - "azure"
           - "aws"
         default: "azure"
-      workerNodesCount:
-        description: "Number of worker nodes to spawn."
-        default: "2"
-      controlNodesCount:
-        description: "Number of control-plane nodes to spawn."
-        default: "3"
+      nodeCount:
+        description: "Number of nodes to use in the cluster. Given in format `<control-plane nodes>:<worker nodes>`."
+        default: "3:2"
+        type: string
       fromVersion:
         description: CLI version to create a new cluster with. This has to be a released version, e.g., 'v2.1.3'.
         type: string
@@ -42,25 +40,19 @@ on:
         description: Enter a version to build the CLI with. This can be used to simulate a patch-upgrade.
         type: string
         required: false
-      scheduled:
-        description: Don't set this when triggering manually.
-        type: boolean
-        default: false
-        required: false
+      regionZone:
+        description: "Region or zone to create the cluster in. Leave empty for default region/zone."
+        type: string
   workflow_call:
     inputs:
       cloudProvider:
         description: "Which cloud provider to use."
         type: string
         required: true
-      workerNodesCount:
-        description: "Number of worker nodes to spawn."
-        type: number
-        required: true
-      controlNodesCount:
-        description: "Number of control-plane nodes to spawn."
-        type: number
-        required: true
+      nodeCount:
+        description: "Number of nodes to use in the cluster. Given in format `<control-plane nodes>:<worker nodes>`."
+        default: "3:2"
+        type: string
       fromVersion:
         description: CLI version to create a new cluster with. This has to be a released version, e.g., 'v2.1.3'.
         type: string
@@ -93,6 +85,32 @@ on:
         required: false
 
 jobs:
+  split-nodeCount:
+    name: Split nodeCount
+    runs-on: ubuntu-22.04
+    permissions:
+      id-token: write
+      contents: read
+    outputs:
+      workerNodes: ${{ steps.split-nodeCount.outputs.workerNodes }}
+      controlPlaneNodes: ${{ steps.split-nodeCount.outputs.controlPlaneNodes }}
+    steps:
+      - name: Split nodeCount
+        id: split-nodeCount
+        shell: bash
+        run: |
+          nodeCount="${{ inputs.nodeCount }}"
+          workerNodes="${nodeCount##*:}"
+          controlPlaneNodes="${nodeCount%%:*}"
+
+          if [[ -z "${workerNodes}" ]] || [[ -z "{controlPlaneNodes}" ]]; then
+            echo "Invalid nodeCount input: '${nodeCount}'."
+            exit 1
+          fi
+
+          echo "workerNodes=${workerNodes}" | tee -a "$GITHUB_OUTPUT"
+          echo "controlPlaneNodes=${controlPlaneNodes}" | tee -a "$GITHUB_OUTPUT"
+
   e2e-upgrade:
     runs-on: ubuntu-22.04
     permissions:
@@ -100,6 +118,7 @@ jobs:
       checks: write
       contents: read
       packages: write
+    needs: [split-nodeCount]
     steps:
       - name: Checkout
         if: inputs.gitRef == 'head'
@@ -139,12 +158,13 @@ jobs:
         id: e2e_test
         uses: ./.github/actions/e2e_test
         with:
-          workerNodesCount: ${{ inputs.workerNodesCount }}
-          controlNodesCount: ${{ inputs.controlNodesCount }}
+          workerNodesCount: ${{ needs.split-nodeCount.outputs.workerNodes }}
+          controlNodesCount: ${{ needs.split-nodeCount.outputs.controlPlaneNodes }}
           cloudProvider: ${{ inputs.cloudProvider }}
           osImage: ${{ inputs.fromVersion }}
           isDebugImage: "false"
           cliVersion: ${{ inputs.fromVersion }}
+          regionZone: ${{ inputs.regionZone }}
           gcpProject: ${{ secrets.GCP_E2E_PROJECT }}
           gcpClusterCreateServiceAccount: "constellation-e2e-cluster@constellation-331613.iam.gserviceaccount.com"
           gcpIAMCreateServiceAccount: "constellation-iam-e2e@constellation-331613.iam.gserviceaccount.com"
@@ -218,8 +238,8 @@ jobs:
           IMAGE: ${{ inputs.toImage && inputs.toImage || steps.find-image.outputs.output }}
           KUBERNETES: ${{ inputs.toKubernetes }}
           MICROSERVICES: ${{ inputs.toMicroservices }}
-          WORKERNODES: ${{ inputs.workerNodesCount }}
-          CONTROLNODES: ${{ inputs.controlNodesCount }}
+          WORKERNODES:  ${{ needs.split-nodeCount.outputs.workerNodes }}
+          CONTROLNODES: ${{ needs.split-nodeCount.outputs.controlPlaneNodes }}
         run: |
           echo "Image target: $IMAGE"
           echo "K8s target: $KUBERNETES"
@@ -278,7 +298,7 @@ jobs:
           failure() &&
           github.ref == 'refs/heads/main' &&
           github.event_name == 'workflow_call' &&
-          inputs.scheduled == 'true'
+          ${{ inputs.scheduled || 'true' }} == 'true'
         continue-on-error: true
         uses: ./.github/actions/notify_failure
         with:
